[build]
  command = "npm run build-prod"
  publish = "build"
  base = "/"

[context.production.environment]
  API_KEY = "AIzaSyAOgvVGGvDAMp_7O4FnZk86hgOuqw80e1c"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200